To see more info on any function, place the blinking cusor before the function brackets and press shift+tab

In [1]:
#To use the numpy Library, you must initially import it
import numpy as np

In [2]:
#creating an array (An Array must have the same data type, most operations performed with arrays are mathematical Ops.
List = [1,2,23,45,4,7,8]
#a data type can be passed to the array function as a parameter. The datatypes are int,float,str,complex
array = np.array(List, dtype = complex)

In [3]:
#to check the type of data an array is
type(array)

numpy.ndarray

In [4]:
print(array)

[ 1.+0.j  2.+0.j 23.+0.j 45.+0.j  4.+0.j  7.+0.j  8.+0.j]


In [5]:
array.shape

(7,)

In [6]:
#instead of just creating a list variable and passing it to the array fxn, you can pass the list into the array directly.
#when one of the elements is a float type, all elements take the float dtype(also applicable to complex dtype.
np.array([1.0,3.0,4.0,7.0+0.j,9])

array([1.+0.j, 3.+0.j, 4.+0.j, 7.+0.j, 9.+0.j])

In [7]:
#multiple lists can be created and passed to the array function as shown below
List1 = [1,2,3,4,5]
List2 = [6,7,8,9,10]
List3 = [11,12,13,14,15]
List4 = [16,17,18,19,20]
arr = np.array([List1,List2,List3,List4])

In [8]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [9]:
# The shape function returns the number of rows and columns in an array 
arr.shape

(4, 5)

In [10]:
#the reshape fxn changes the array to a desired shape(i.e number of rows and columns) 
#provided that it's a multiple of the original array
arr.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [11]:
#Accessing a multidimensional array using row index and column index
#[row index,column index] in both cases a:b mean from index "a" to index "b-1"
#When no number is passed for example [:] it means accesss everything
#when no ending is specified for example [a:] it means from index "a" to the last element 
arr[0:3,0:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [12]:
#A 1D array can be created by using the np.arange fxn which recieves the start and end, interval(step) and also the dtype
arr = np.arange(0,10, step = 1.5, dtype = float)
print(arr)

[0.  1.5 3.  4.5 6.  7.5 9. ]


In [13]:
#This function linspace() Return evenly spaced numbers over a specified interval
#It recieves the starting and ending numbers,number of values with decimals to be generated and other parameters
#(press shift+tab before parenthesis of the function to see more info
array7 = np.linspace(0,10,10)
print(array7)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [14]:
#the example below is called broadcasting i.e changing the element of an array
array7[2:9] = 20
print(array7)

[ 0.          1.11111111 20.         20.         20.         20.
 20.         20.         20.         10.        ]


In [15]:
#Scalar arithemtic operations can be performed on an array, for example:
arr3 = np.array([1,2,3,4,5,6,7,8,9])
add = arr3 + 3
print("This is for addition ",add)
sub = arr3 - 2
print("This is for subtraction", sub)
#other operations can be performed in a similar manner

This is for addition  [ 4  5  6  7  8  9 10 11 12]
This is for subtraction [-1  0  1  2  3  4  5  6  7]


In [16]:
#Conditional operations can also be performed, for example:
less = arr3[arr3<4]
print("This is for less than", less)
greater = arr3[arr3>3]
print("This is for greater than", greater)
#other operations like "!=","==", "<=", and "=>" can be performed in a similar manner
#also multiple conditional statements can be passed within the square braces

This is for less than [1 2 3]
This is for greater than [4 5 6 7 8 9]


In [17]:
#to create array with one as all it's element, the function np.ones() is used for example
#the funcion recieves the shape of the array and dtype(optional) as it's by default set to float
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [18]:
#if the array has some numbers of rows and columns, it should be passed to the function as (a,b) 
# as "a" is the number of rows and "b" is the nummber of columns
np.ones((3,4), dtype = complex)

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]])

In [19]:
#This function create an array of the given shape and populate it with
#random samples from a uniform distribution that is within 0 and 1
np.random.rand(4,3)

array([[0.79697599, 0.04562935, 0.01973718],
       [0.77031181, 0.12520393, 0.3587778 ],
       [0.69832968, 0.47332787, 0.53652241],
       [0.73850921, 0.89966516, 0.63875868]])

In [20]:
np.random.randn(4,2)

array([[ 0.62415196, -0.17151261],
       [ 1.01680841,  1.52992166],
       [ 0.4479357 ,  1.21069811],
       [ 1.78609577,  0.78107127]])

In [21]:
#this function recieves the range of values the random no. will be selected from and also how many numbers will be slected
#the data type is always int
np.random.randint(1,100,10).reshape(2,5)

array([[31, 30, 81, 22, 61],
       [67, 55, 16, 29, 77]])